### ISSUE TITLE
Boot failed on Joule

### ISSUE THREAD

**Issue by minggangw** [intel/intel-iot-refkit#118]
Hi,

I'm trying to build and install the image on Joule board. Following the [build](https://github.com/intel/intel-iot-refkit/blob/master/README.rst) and [install](https://github.com/intel/intel-iot-refkit/blob/master/doc/howtos/image-install.rst) instructions, I can boot the Joule, but always stay at

`random: crng init done` 

I built without docker (develop build with default `local.conf`) and use `dd` to create a bootable usb. During the booting process, no error is reported. Does anyone know what's the problem here?

Thanks in advance!

**Comment by mythi** [comment]
@minggangw What's your console setup (display and/or serial)? What's your BIOS version?

**Comment by minggangw** [comment]
Hi @mythi thanks for your tips. I check the BIOS version, which is B30.1611152208, and I flashed the latest 1D1. The Joule can boot now! So I close this issue.
