### ISSUE TITLE
Fail to build refkit image with docker

### ISSUE THREAD

**Issue by ttzeng** [intel/intel-iot-refkit#128]
Tried to build refkit image with docker per README.rst, and run into below error. What am I missing? Any pointer would be appreciated. Thanks.

[tzeng@ttzeng-desktop:~/Workspace/yocto/ref-os-iot/intel-iot-refkit]
$ git rev-parse HEAD
90c6298aa28f4bfd62380914ca37f335a7a5a37c
[tzeng@ttzeng-desktop:~/Workspace/yocto/ref-os-iot/intel-iot-refkit]
$ docker/local-build.sh refkit-image-common
unable to prepare context: unable to evaluate symlinks in context path: lstat /home/tzeng/Workspace/yocto/refkit-intel-corei7-64/docker: no such file or directory
Unable to find image 'refkit:latest' locally
Pulling repository docker.io/library/refkit
docker: Error: image library/refkit:latest not found.
See 'docker run --help'.

**Comment by okartau** [comment]
are you sure that this clean environment containing only refkit tree and no other elements,symlinks mixed into directory structure, PATH ?
If Workspace/yocto/ref-os-iot/intel-iot-refkit is your WORKSPACE,
then why is error msg referring to Workspace/yocto/refkit-intel-corei7-64/docker ?

Path reported in error msg: Workspace/yocto/refkit-intel-corei7-64/ should not become part of picture,
unless something goes wrong, as this is two directory levels up from workspace.

**Comment by ttzeng** [comment]
@okartau Thanks for responding, I misunderstood the env variable 'WORKSPACE', I set it wrong to my build folder containing my bblaybers.conf and additional recipes... BTW, what's the proper way to add my recipes on refkit with docker build? i.e. how to direct the build using my local.conf and bblayers.conf?  Thanks.

**Comment by okartau** [comment]
Use of docker should not add any extra complexity, docker just encapsulates build host side and makes it standard, i.e. same which is tried in refkit CI on every change.
Whole workspace is passed into docker as it is, so you should not worry how things work "with docker", as they should work just as without docker.

**Comment by okartau** [comment]
For adding a layer, use "bitbake-layers add-layer" after call of init script (refkit-init-build-env ) and before call to bitbake, in docker/build-project.sh.

local.conf and bblayers.conf are not modified by refkit build script.

auto.conf is totally created/modified by build-project.sh, check it if you need changes there.

overall: build-project.sh is the script you want to check. Most of it's lines are only activating in  CI builds,
so it's actually small part relevant there in local-build case.
local-build.sh starts a docker session which runs build-project.sh.

**Comment by ttzeng** [comment]
Thank you @okartau for the instructions, and sorry for the false alarm.

**Comment by mythi** [comment]
@ttzeng can we close this?
