### ISSUE TITLE
Variables not set by default but still used

### ISSUE THREAD

**Issue by tripzero** [intel/intel-iot-refkit#154]
a distro cannot use meta-refkit as a layer because a number of variables aren't being set because they rely on a specific local.conf (or include from local.conf)

REFKIT_DMVERITY_PRIVATE_KEY 

Full error: 

ERROR: /path/../meta-refkit/recipes-image/images/initramfs-framework-refkit-dm-verity.bb: REFKIT_DMVERITY_PRIVATE_KEY is not set.
ERROR: ExpansionError during parsing /path/intel-iot-refkit/openembedded-core/../meta-refkit/recipes-image/images/refkit-image-gateway.bb

REFKIT_USE_DSK_IMAGES

ERROR: ExpansionError during parsing /path/meta-refkit/recipes-image/images/refkit-image-gateway.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable IMAGE_CLASSES, expression was  qemuboot qemuboot ${@ 'image-dsk' if ${REFKIT_USE_DSK_IMAGES} else ''} image_types which triggered exception SyntaxError: invalid syntax (IMAGE_CLASSES, line 1)

**Comment by mythi** [comment]
It works if you use 'refkit' distro and add the necessary .inc files in your local.conf. I'd think this is an OK expectation from a distro layer.

We are aware of the issue that the layer provides content/middleware others might be willing to use. Work is ongoing to fix that. 

What content are you looking to use?

**Comment by tripzero** [comment]
mostly the stuff in recipes-sensors, but dsk images are also interesting among other things.  I'm trying to investigate whether or not the way refkit keeps up-to-date submodules of the other layers with built-in checks and QA is leveragable by another distro layer.

**Comment by pohly** [comment]
@tripzero: please have a look at PR #147. It's where we try to make our content (including image-dsk.bbclass) available to other projects and distros.

**Comment by mythi** [comment]
what's in HEAD should fix the problems
