### ISSUE TITLE
mraa doesn't compile python3 bindings.

### ISSUE THREAD

**Issue by tripzero** [intel/intel-iot-refkit#249]
because recipe inherits "distutils-base" instead of "distutils3-base", only python2 bindings are created. 
 mraa supports building for both python2 and 3, but recipe doesn't support it.

**Comment by rojkov** [comment]
The `mraa` recipe used in Refkit inherits distutils3-base:
https://github.com/intel/intel-iot-refkit/blob/master/meta-refkit-core/recipes-sensors/mraa/mraa_git.bb#L15

**Comment by tripzero** [comment]
Great.  Looks like ref-os-iot is just out of sync.
