### ISSUE TITLE
No npm in gateway image

### ISSUE THREAD

**Issue by uhofemei** [intel/intel-iot-refkit#84]
I'm using the latest RefKit gateway image with the IoT to Cloud Smart Home demo. Good news is: I'm able to run the IoT REST API service fine with the stock image configuration. Good work guys 👍  

What I would like to do is run the "cloud side" docker app to access the REST API. Unfortunately the requirements to install the binary version of Docker on RefKit aren't met. According to the Docker documentation a few packages are missing in the image:

https://docs.docker.com/engine/installation/binaries/#install-daemon-and-client-binaries-on-linux

What do you think about generating one dev image that can be used to modify and debug code on target regardless of the RefKit profile that is being used? Such an image should contain Autotools, compiler, git, all editors for Linux and header files for all packages, etc. Yes, the image would be rather large, but installing a large image installed once still beats the task to generate image(s) for the purpose of on-target development by far :-)

**Comment by gvancuts** [comment]
Can we update the issue title to reflect the content?

**Comment by uhofemei** [comment]
RefKit issues are now being tracked in the IoT Reference OS Kit product as part of the Yocto project bugzilla. Closing this issue.
